/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\syed shabab haider\Desktop\3D Builder\Frontend\public\PRODUCTS\AMERICAN FOOTBALL\AMERICAN FOOTBALL JERSEY.glb -o C:\Users\syed shabab haider\Desktop\3D Builder\Frontend\src\components\PRODUCTS\AMERICAN FOOTBALL\AmericanFootballJersey.jsx --root public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/PRODUCTS/AMERICAN FOOTBALL/AMERICAN FOOTBALL JERSEY.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cloth_mesh.geometry}
        material={materials["FABRIC 2_2565"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_1.geometry}
        material={materials["FABRIC 2_2565"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_2.geometry}
        material={materials["FABRIC 2_2565"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_3.geometry}
        material={materials["FABRIC 2_2565"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_4.geometry}
        material={materials["FABRIC 2_2565"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_5.geometry}
        material={materials["FABRIC 2_2565"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_6.geometry}
        material={materials["FABRIC 2_2565"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_7.geometry}
        material={materials["FABRIC 2_2565"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_8.geometry}
        material={materials["FABRIC 2_2565"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_9.geometry}
        material={materials["FABRIC 2_2565"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_10.geometry}
        material={materials["FABRIC 2_2565"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_11.geometry}
        material={materials["FABRIC 2_2565"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_12.geometry}
        material={materials["FABRIC 2_2565"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_13.geometry}
        material={materials["FABRIC 2_2565"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_14.geometry}
        material={materials["FABRIC 2_2565"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_15.geometry}
        material={materials["FABRIC 2_2565"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_16.geometry}
        material={materials["FABRIC 2_2565"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_17.geometry}
        material={materials["FABRIC 2_2565"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_18.geometry}
        material={materials["FABRIC 2_2565"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_19.geometry}
        material={materials["FABRIC 2_2565"]}
      />
    </group>
  );
}

useGLTF.preload("/PRODUCTS/AMERICAN FOOTBALL/AMERICAN FOOTBALL JERSEY.glb");
