/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\syed shabab haider\Desktop\3D Builder\Frontend\public\PRODUCTS\SPORTS WEARS\HODIES.glb -o C:\Users\syed shabab haider\Desktop\3D Builder\Frontend\src\components\PRODUCTS\SPORTS WEARS\Hodies.jsx --root public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/PRODUCTS/SPORTS WEARS/HODIES.glb')
  return (
    <group {...props} dispose={null}>
      {/* Sleeves */}
      <mesh
        geometry={nodes.Cloth_mesh.geometry}
        material={materials["FABRIC 1_30401"]}
      >
        <meshStandardMaterial
          {...materials.body_mat}
          color={"red"}
        />
      </mesh>
      <mesh
        geometry={nodes.Cloth_mesh_1.geometry}
        material={materials["FABRIC 1_30401"]}
      >
        <meshStandardMaterial
          {...materials.body_mat}
          color={"red"}
        />
      </mesh>

      {/* Sleeve Hem */}
      <mesh
        geometry={nodes.Cloth_mesh_7.geometry}
        material={materials["FABRIC 1_30401"]}
      >
        {" "}
        <meshStandardMaterial {...materials.body_mat} color={"red"} />
      </mesh>
      <mesh
        geometry={nodes.Cloth_mesh_8.geometry}
        material={materials["FABRIC 1_30401"]}
      >
        <meshStandardMaterial {...materials.body_mat} color={"red"} />
      </mesh>

      {/* Body */}
      <mesh
        geometry={nodes.Cloth_mesh_2.geometry}
        material={materials["FABRIC 1_30401"]}
      >
        <meshStandardMaterial {...materials.body_mat} color={"red"} />
      </mesh>
      <mesh
        geometry={nodes.Cloth_mesh_9.geometry}
        material={materials["FABRIC 1_30401"]}
      >
        <meshStandardMaterial {...materials.body_mat} color={"red"} />
      </mesh>

      {/* Pockets */}
      <mesh
        geometry={nodes.Cloth_mesh_10.geometry}
        material={materials["FABRIC 1_30401"]}
      >
        <meshStandardMaterial
          {...materials.body_mat}
          color={"red"}
        />
      </mesh>

      {/* Body Hem */}
      <mesh
        geometry={nodes.Cloth_mesh_6.geometry}
        material={materials["FABRIC 1_30401"]}
      >
        <meshStandardMaterial {...materials.body_mat} color={"red"} />
      </mesh>
      {/* Hood */}
      <mesh
        geometry={nodes.Cloth_mesh_3.geometry}
        material={materials["FABRIC 1_30401"]}
      >
        <meshStandardMaterial {...materials.body_mat} color={"red"} />
      </mesh>
      <mesh
        geometry={nodes.Cloth_mesh_4.geometry}
        material={materials["FABRIC 1_30401"]}
      >
        <meshStandardMaterial {...materials.body_mat} color={"red"} />
      </mesh>

      <mesh
        geometry={nodes.Cloth_mesh_5.geometry}
        material={materials["FABRIC 1_30401"]}
      />
    </group>
  );
}

useGLTF.preload('/PRODUCTS/SPORTS WEARS/HODIES.glb')
