/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\syed shabab haider\Desktop\3D Builder\Frontend\public\PRODUCTS\SPORTS WEARS\HODIES SHIRTS SHOTING SHIRTS.glb -o C:\Users\syed shabab haider\Desktop\3D Builder\Frontend\src\components\PRODUCTS\SPORTS WEARS\HodiesShirtsShotingShirts.jsx --root public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/PRODUCTS/SPORTS WEARS/HODIES SHIRTS SHOTING SHIRTS.glb')
  return (
    <group {...props} dispose={null}>
      {/* Body */}
      <mesh
        geometry={nodes.Cloth_mesh.geometry}
        material={materials["FABRIC 2_2562"]}
      >
        <meshStandardMaterial
          {...materials.body_mat}
          color={"red"}
        />
      </mesh>
      <mesh
        geometry={nodes.Cloth_mesh_1.geometry}
        material={materials["FABRIC 2_2562"]}
      >
        <meshStandardMaterial
          {...materials.body_mat}
          color={"red"}
        />
      </mesh>
      {/* Sleeves */}
      <mesh
        geometry={nodes.Cloth_mesh_2.geometry}
        material={materials["FABRIC 2_2562"]}
      >
        <meshStandardMaterial
          {...materials.body_mat}
          color={"red"}
        />
      </mesh>
      <mesh
        geometry={nodes.Cloth_mesh_3.geometry}
        material={materials["FABRIC 2_2562"]}
      >
        <meshStandardMaterial
          {...materials.body_mat}
          color={"red"}
        />
      </mesh>
      {/* Hood */}
      <mesh
        geometry={nodes.Cloth_mesh_4.geometry}
        material={materials["FABRIC 2_2562"]}
      >
        <meshStandardMaterial
          {...materials.body_mat}
          color={"red"}
        />
      </mesh>
      <mesh
        geometry={nodes.Cloth_mesh_5.geometry}
        material={materials["FABRIC 2_2562"]}
      >
        <meshStandardMaterial
          {...materials.body_mat}
          color={"red"}
        />
      </mesh>

      <mesh
        geometry={nodes.Cloth_mesh_6.geometry}
        material={materials["FABRIC 2_2562"]}
      ></mesh>
    </group>
  );
}

useGLTF.preload('/PRODUCTS/SPORTS WEARS/HODIES SHIRTS SHOTING SHIRTS.glb')
