/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\syed shabab haider\Desktop\3D Builder\Frontend\public\PRODUCTS\SPORTS WEARS\SLEEVELESS HODIES.glb -o C:\Users\syed shabab haider\Desktop\3D Builder\Frontend\src\components\PRODUCTS\SPORTS WEARS\SleevelessHodies.jsx --root public 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/PRODUCTS/SPORTS WEARS/SLEEVELESS HODIES.glb",
  );
  return (
    <group {...props} dispose={null}>
      {/* Body */}
      <mesh
        geometry={nodes.Cloth_mesh.geometry}
        material={materials["FABRIC 1_39604"]}
      >
        <meshStandardMaterial {...materials.body_mat} color={"red"} />
      </mesh>
      <mesh
        geometry={nodes.Cloth_mesh_4.geometry}
        material={materials["FABRIC 1_39604"]}
      >
        <meshStandardMaterial {...materials.body_mat} color={"red"} />
      </mesh>
      {/* Hood */}
      <mesh
        geometry={nodes.Cloth_mesh_1.geometry}
        material={materials["FABRIC 1_39604"]}
      >
        <meshStandardMaterial {...materials.body_mat} color={"red"} />
      </mesh>
      <mesh
        geometry={nodes.Cloth_mesh_2.geometry}
        material={materials["FABRIC 1_39604"]}
      >
        <meshStandardMaterial {...materials.body_mat} color={"red"} />
      </mesh>

      <mesh
        geometry={nodes.Cloth_mesh_3.geometry}
        material={materials["FABRIC 1_39604"]}
      ></mesh>

      {/* Shoulder border */}

      <mesh
        geometry={nodes.Cloth_mesh_5.geometry}
        material={materials["FABRIC 1_39604"]}
      >
        <meshStandardMaterial {...materials.body_mat} color={"red"} />
      </mesh>
      <mesh
        geometry={nodes.Cloth_mesh_6.geometry}
        material={materials["FABRIC 1_39604"]}
      >
        <meshStandardMaterial {...materials.body_mat} color={"red"} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/PRODUCTS/SPORTS WEARS/SLEEVELESS HODIES.glb");
