/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\syed shabab haider\Desktop\3D Builder\Frontend\public\PRODUCTS\BASEBALL\CREW NECK JERSEYS.glb -o C:\Users\syed shabab haider\Desktop\3D Builder\Frontend\src\components\PRODUCTS\BASEBALL\CrewNeckJerseys.jsx --root public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/PRODUCTS/BASEBALL/CREW NECK JERSEYS.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cloth_mesh.geometry} material={materials['FABRIC 1_2562']} />
      <mesh geometry={nodes.Cloth_mesh_1.geometry} material={materials['FABRIC 1_2562']} />
      <mesh geometry={nodes.Cloth_mesh_2.geometry} material={materials['FABRIC 1_2562']} />
      <mesh geometry={nodes.Cloth_mesh_3.geometry} material={materials['FABRIC 1_2562']} />
      <mesh geometry={nodes.Cloth_mesh_4.geometry} material={materials['FABRIC 1_2562']} />
    </group>
  )
}

useGLTF.preload('/PRODUCTS/BASEBALL/CREW NECK JERSEYS.glb')
