/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\syed shabab haider\Desktop\3D Builder\Frontend\public\PRODUCTS\BASEBALL\FULL BUTTON JERSEY.glb -o C:\Users\syed shabab haider\Desktop\3D Builder\Frontend\src\components\PRODUCTS\BASEBALL\FullButtonJersey.jsx --root public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/PRODUCTS/BASEBALL/FULL BUTTON JERSEY.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cloth_mesh.geometry} material={materials['FABRIC 2_2565']} />
      <mesh geometry={nodes.Cloth_mesh_1.geometry} material={materials['FABRIC 2_2565']} />
      <mesh geometry={nodes.Cloth_mesh_2.geometry} material={materials['Default Buttonhole_2660']} />
      <mesh geometry={nodes.Cloth_mesh_3.geometry} material={materials['Default Buttonhole_2660']} />
      <mesh geometry={nodes.Cloth_mesh_4.geometry} material={materials['Default Buttonhole_2660']} />
      <mesh geometry={nodes.Cloth_mesh_5.geometry} material={materials['Default Buttonhole_2660']} />
      <mesh geometry={nodes.Cloth_mesh_6.geometry} material={materials['Default Buttonhole_2660']} />
      <mesh geometry={nodes.Cloth_mesh_7.geometry} material={materials['Default Buttonhole_2660']} />
      <mesh geometry={nodes.Cloth_mesh_8.geometry} material={materials['FABRIC 2_2565']} />
      <mesh geometry={nodes.Cloth_mesh_9.geometry} material={materials['FABRIC 2_2565']} />
      <mesh geometry={nodes.Cloth_mesh_10.geometry} material={materials['FABRIC 2_2565']} />
      <mesh geometry={nodes.Cloth_mesh_11.geometry} material={materials['FABRIC 2_2565']} />
      <mesh geometry={nodes.Cloth_mesh_12.geometry} material={materials['FABRIC 2_2565']} />
      <mesh geometry={nodes.Cloth_mesh_13.geometry} material={materials['FABRIC 2_2565']} />
      <group position={[0.005, 1.512, 0.08]} rotation={[1.28, 0.004, -0.471]}>
        <mesh geometry={nodes.Button_179999.geometry} material={materials['1_Sew-through_Button_01_Cross_2567']} />
        <mesh geometry={nodes.Button_179999_1.geometry} material={materials['1_Sew-through_Button_01_Cross_2567']} />
      </group>
      <group position={[0.005, 1.411, 0.107]} rotation={[1.383, -0.061, -0.283]}>
        <mesh geometry={nodes.Button_181850.geometry} material={materials['1_Sew-through_Button_01_Cross_2567']} />
        <mesh geometry={nodes.Button_181850_1.geometry} material={materials['1_Sew-through_Button_01_Cross_2567']} />
      </group>
      <group position={[0.004, 1.321, 0.125]} rotation={[1.347, 0.113, -0.285]}>
        <mesh geometry={nodes.Button_182682.geometry} material={materials['1_Sew-through_Button_01_Cross_2567']} />
        <mesh geometry={nodes.Button_182682_1.geometry} material={materials['1_Sew-through_Button_01_Cross_2567']} />
      </group>
      <group position={[0.003, 1.227, 0.139]} rotation={[1.498, 0.025, -0.27]}>
        <mesh geometry={nodes.Button_183675.geometry} material={materials['1_Sew-through_Button_01_Cross_2567']} />
        <mesh geometry={nodes.Button_183675_1.geometry} material={materials['1_Sew-through_Button_01_Cross_2567']} />
      </group>
      <group position={[0.003, 1.132, 0.145]} rotation={[1.462, 0.065, -0.407]}>
        <mesh geometry={nodes.Button_184609.geometry} material={materials['1_Sew-through_Button_01_Cross_2567']} />
        <mesh geometry={nodes.Button_184609_1.geometry} material={materials['1_Sew-through_Button_01_Cross_2567']} />
      </group>
      <group position={[0, 1.032, 0.148]} rotation={[1.348, 0.016, -0.592]}>
        <mesh geometry={nodes.Button_185784.geometry} material={materials['1_Sew-through_Button_01_Cross_2567']} />
        <mesh geometry={nodes.Button_185784_1.geometry} material={materials['1_Sew-through_Button_01_Cross_2567']} />
      </group>
    </group>
  )
}

useGLTF.preload('/PRODUCTS/BASEBALL/FULL BUTTON JERSEY.glb')
