/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\syed shabab haider\Desktop\3D Builder\Frontend\public\PRODUCTS\ICE HOCKEY\JERSEYS.glb -o C:\Users\syed shabab haider\Desktop\3D Builder\Frontend\src\components\PRODUCTS\ICE HOCKEY\Jerseys.jsx --root public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF("/PRODUCTS/ICE HOCKEY/JERSEYS.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cloth_mesh.geometry}
        material={materials["FABRIC 2_2562"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_1.geometry}
        material={materials["FABRIC 2_2562"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_2.geometry}
        material={materials["FABRIC 2_2562"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_3.geometry}
        material={materials["FABRIC 2_2562"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_4.geometry}
        material={materials["FABRIC 2_2562"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_5.geometry}
        material={materials["FABRIC 2_2562"]}
      />
    </group>
  );
}

useGLTF.preload('/PRODUCTS/ICE HOCKEY/JERSEYS.glb')
