/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\syed shabab haider\Desktop\3D Builder\Frontend\public\PRODUCTS\BASKETBALL\SINGLE BASKETBALL V NECK.glb -o C:\Users\syed shabab haider\Desktop\3D Builder\Frontend\src\components\PRODUCTS\BASKETBALL\SingleBasketballVNeck.jsx --root public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/PRODUCTS/BASKETBALL/SINGLE BASKETBALL V NECK.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cloth_mesh.geometry} material={materials['FABRIC 1_2574']} />
      <mesh geometry={nodes.Cloth_mesh_1.geometry} material={materials['FABRIC 1_2574']} />
      <mesh geometry={nodes.Cloth_mesh_2.geometry} material={materials['FABRIC 1_2574']} />
      <mesh geometry={nodes.Cloth_mesh_3.geometry} material={materials['FABRIC 1_2574']} />
      <mesh geometry={nodes.Cloth_mesh_4.geometry} material={materials['FABRIC 1_2574']} />
    </group>
  )
}

useGLTF.preload('/PRODUCTS/BASKETBALL/SINGLE BASKETBALL V NECK.glb')
